"""
File for setting all parameters for the master project. All changes and variables is set here
"""


# Preprocessing
fps: 10  # Sampling frequency for video to frames

convert_videos_to_frames: False  # Convert to frames or not
label_the_frames: False  # Crop, scale and label the frames
relabel_the_frames: False

# Data Augmentation
frame_dimension = (384, 384)  # Dimension of the scaled frames that will be sent into CNN

# Datasets
dataset_type = 'synthetic'  # {'synthetic' 'human'}
test_split = 0.1  # Fraction that split data into test data
validation_split = 0.2  # Fraction that split data into validation data
num_frames_in_stack = 5  # Num frames in a stack that gets sent into RNN
slide_ratio_in_stack = 10  # Ratio of slide between frames in a stack
split_the_data = False  # Split videos into train, test or validation
shuffle_dataset = True

# Neural nets details
num_airway_segment_classes = 27
num_direction_classes = 2
hidden_nodes = 64
num_features = 256
num_LSTM_cells = 5

# Training specifications
perform_training = True
os.environ["CUDA_VISIBLE_DEVICES"] = "0"  # "0" or "1"
epochs = 2000
batch_size = 16
#accum_iter = 4  # batch accumulation parameter
learning_rate = 1e-3
early_stop_count = 20
num_stacks = 1024  # Must be divisible by batch size
num_validations = 100  # Num times for validation our model during training
alpha = 0.25
gamma = 2.0
test_slide_ratio_in_stack = 10
use_focal_loss = False

# Testing trained model
load_best_model = True
get_data_dist = False
get_loss_and_accuracy = False
get_confusion_metrics = False
get_testset_pred = False
get_f1_score = False
convert_to_onnx = False

# Data paths
root_directory_path = "/cluster/home/ingrikol/master"
data_path = f"{root_directory_path}/data/{dataset_type}"
videos_path = f"{data_path}/{dataset_type}_videos/"
frames_path = f"{data_path}/{dataset_type}_frames"
label_file_path = f"{data_path}/labeling_info/{dataset_type}_branches_positions_numbers.txt"
names_file_path = f"{data_path}/labeling_info/{dataset_type}_branch_number_name.txt"
csv_videos_path = f"{data_path}/videos_csv/"
relabeled_csv_videos_path = f"{data_path}/relabeled_videos_csv/"
dataset_path = f"{data_path}/datasets/"

# Training and Testing paths
model_type = "baseline"
date_and_time = datetime.now().strftime('%d-%m-%Y_%H-%M-%S')
train_plot_path = f"{root_directory_path}/plots/training/"
train_plot_name = f"{date_and_time}_{dataset_type}_{model_type}_fps_{fps}"
test_plot_path = f"{root_directory_path}/plots/testing/"
confusion_metrics_name = f"{date_and_time}_confusion_metrics_{dataset_type}_{model_type}_fps_{fps}"
model_path = f"{root_directory_path}/models/"
model_name = f"frames_{num_frames_in_stack}_slide_{slide_ratio_in_stack}_stacks_{num_stacks}_features_{num_features}_LSTM_cells_{num_LSTM_cells}_batchsize_{batch_size}_epochs_{epochs}_focal_loss_{use_focal_loss}"
#model_name = f"{date_and_time}_{model_type}_fps_{fps}"

